server:
  port: 3000
spring:
  application:
    name: springauth
  data:
    mongodb:
      uri: mongodb://localhost:27017/PAWA-metro
      database: metroproject
  stripe:
    secret-key: ${STRIPE_SECRET_KEY}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
